name: Deploy to VPS

on:
  push:
    branches:
      - desenvolvimento

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e  # Se der erro, para tudo

            echo "ðŸ“¦ Indo para o projeto"
            cd /var/www/agendoai-app-prod || exit

            echo "ðŸ”„ Dando git pull"
            git pull origin desenvolvimento

            echo "ðŸ“ Buildando frontend"
            cd client
            npm install
            NODE_OPTIONS="--max-old-space-size=4096" npm run build

            echo "ðŸ”™ Voltando para backend"
            cd ..

            echo "ðŸ“¦ Instalando dependÃªncias do backend"
            npm install

            echo "ðŸš€ Reiniciando backend com PM2"
            pm2 restart agendoai-backend
          EOF
